### ISSUE TITLE
CustomController with no respective view created return random error

### ISSUE THREAD

**Issue by djavier** [markmercedes/krudmin#104]
After adding a new controller inheriting `Krudmin:CustomController`  and no views created yet,
the following error is shown, instead of a more guiding error about the resource missing: 
![image](https://user-images.githubusercontent.com/1663038/38897700-51743634-4262-11e8-9566-1b623fad8886.png)

And it is actually misleading because `Krudmin:CustomController`  is not supposed to be controlled by a ResourceManager, yet the error says is looking for one.

**Comment by markmercedes** [comment]
@djavier it comes down to inheritance, since the CustomController inherits from the application controller, the application controller will try to render the `application/index` view, basically there will always be a view available for rendition. I'll perform a little decoupling in the `KrudminControllerSupport` concern in order to exclude resource manager related methods from custom controllers.
