### ISSUE TITLE
Display attribute label instead of the attribute name when a search is applied

### ISSUE THREAD

**Issue by nivla** [markmercedes/krudmin#138]
When a search is applied it should show the label value defined for the attribute if it's defined instead of use the attribute_name

```ruby
  ATTRIBUTE_TYPES = {
      account_full_name: {type: :String, input: { label: "Name" } },
}
```

![screen shot 2018-06-06 at 4 36 19 pm](https://user-images.githubusercontent.com/2448098/41063834-cfc43d88-69a7-11e8-9d4b-a908e8251f60.png)

**Comment by markmercedes** [comment]
@nivla this issue is a little trickier and might be addressed in the future using another approach, I've decided to just display the search form if some user filters are applied.

Building the string that contains the applied search filters has a high complexity and as of now, I don't have a clear solution for the kind of thing I would like to do there.

#140
