### ISSUE TITLE
Create action buttons API

### ISSUE THREAD

**Issue by markmercedes** [markmercedes/krudmin#55]
- Buttons will have internal logic and they will decide wether or not they are displayable based on their context and policy permissions for the given resource

```ruby
class AddButton < Button::Base
  def initialize(policy, action_path)
    @policy, @action_path = policy, action_path
  end

  def to_s
    = link_to(new_resource_path, class: 'btn btn-success') do
      %i.fa.fa-plus
      = t('krudmin.actions.add_new')
  end

  def render
    to_s if policy.new?
  end
end

AddButton.for(policy, new_resource_path)
```

create corresponding view helpers for buttons, this will prevent the need of invoking full names for button classes inside the views

``` ruby
= Krudmin::ActionButtons::AddButton.new(self, new_resource_path)

= add_button(self, new_resource_path)
```

**Comment by markmercedes** [comment]
@djavier taking a deeper look at this feature, pundit dependency will be added directly back to the project if we take the our original approach that injects the policy into the button

**Comment by djavier** [comment]
@markmercedes back to scratch board then.

On Jan 17, 2018 12:23 AM, "Marcos Mercedes" <notifications@github.com>
wrote:

@djavier <https://github.com/djavier> taking a deeper look at this feature,
pundit dependency will be added directly back to the project if we take the
our original approach that injects the policy into the button

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/markmercedes/krudmin/issues/55#issuecomment-358193226>,
or mute the thread

**Comment by markmercedes** [comment]
@djavier updated #60
